start rewrite of script, use rbenv for ruby, tweak a bunch of stuff based on current thoughtbot script

diff --git a/mac b/mac
--- a/mac
+++ b/mac
@@ -1,37 +1,94 @@
 #!/usr/bin/env zsh
 
-successfully() {
-  $* || (echo "failed" 1>&2 && exit 1)
+# Welcome to Matt's laptop script! Forked from thoughbot.
+# Be prepared to turn your laptop (or desktop, no haters here)
+# into an awesome development machine.
+
+trap 'ret=$?; test $ret -ne 0 && printf "failed\n\n" >&2; exit $ret' EXIT
+
+set -e
+### end common-components/exit-trap
+
+if [ ! -d "$HOME/.bin/" ]; then
+  mkdir "$HOME/.bin"
+fi
+
+if [[ ":$PATH:" != *":$HOME/.bin:"* ]]; then
+  echo 'export PATH="$HOME/.bin:$PATH"' >> ~/.zshrc
+  source ~/.zshrc
+fi
+### end common-components/check-home-bin
+
+fancy_echo() {
+  printf "\n%b\n" "$1"
 }
+### end common-components/shared-functions
+
+if [[ -f /etc/zshenv ]]; then
+  fancy_echo "Fixing OSX zsh environment bug ..."
+    sudo mv /etc/{zshenv,zshrc}
+fi
+### end mac-components/zsh-fix
 
 echo "Checking for SSH key, generating one if it doesn't exist ..."
   [[ -f ~/.ssh/id_rsa.pub ]] || ssh-keygen -t rsa
 
-echo "Fixing permissions ..."
-  successfully sudo chown -R `whoami` /usr/local
+fancy_echo "Installing Homebrew, a good OS X package manager ..."
+  ruby <(curl -fsS https://raw.github.com/mxcl/homebrew/go)
+  brew update
 
-echo "Installing Homebrew, a good OS X package manager ..."
-  successfully ruby <(curl -fsS https://raw.github.com/mxcl/homebrew/go)
-  successfully brew update
+if ! grep -qs "recommended by brew doctor" ~/.zshrc; then
+  fancy_echo "Put Homebrew location earlier in PATH ..."
+    echo "\n# recommended by brew doctor" >> ~/.zshrc
+    echo "export PATH='/usr/local/bin:$PATH'\n" >> ~/.zshrc
+    source ~/.zshrc
+fi
 
-echo "Putting Homebrew location earlier in PATH ..."
-  successfully echo "
-# recommended by brew doctor
-export PATH='/usr/local/bin:$PATH'" >> ~/.zshenv
-  successfully source ~/.zshenv
+### end mac-components/homebrew
 
-echo "Installing GNU Compiler Collection and dependencies ..."
-  successfully brew tap homebrew/dupes
-  successfully brew install coreutils
+fancy_echo "Installing GNU Compiler Collection and dependencies ..."
+  brew tap homebrew/dupes
+  brew install coreutils
 
-echo "Installing git, Node.js, Z Script ..."
-  successfully brew install git node z
+fancy_echo "Installing git, Node.js, Z Script ..."
+  brew install git vim node hub z zsh mysql openssl
 
-echo "Installing Essential NPM Packages - Grunt, Yeoman and Bower, because you need them ..."
-  successfully npm install -g yo grunt-cli bower
+fancy_echo "Installing PHP 5.4 ..."
+  brew tap josegonzalez/homebrew-php
+  brew install php54 php54-mcrypt php54-apc
 
-echo "Installing critical Ruby gems for development ..."
-  successfully gem install bundler rails compass --no-rdoc --no-ri
+fancy_echo "Installing rbenv, to change Ruby versions ..."
+  brew install rbenv
 
-echo "Your shell will now restart in order for changes to apply."
-  exec $SHELL -l
+  if ! grep -qs "rbenv init" ~/.zshrc; then
+    echo 'eval "$(rbenv init -)"' >> ~/.zshrc
+
+    fancy_echo "Enable shims and autocompletion ..."
+      eval "$(rbenv init -)"
+  fi
+
+  source ~/.zshrc
+
+fancy_echo "Installing rbenv-gem-rehash so the shell automatically picks up binaries after installing gems with binaries..."
+  brew install rbenv-gem-rehash
+
+fancy_echo "Installing ruby-build, to install Rubies ..."
+  brew install ruby-build
+### end mac-components/rbenv
+
+fancy_echo "Installing Ruby 2.0.0-p247 ..."
+  rbenv install 2.0.0-p247
+
+fancy_echo "Setting Ruby 2.0.0-p247 as global default Ruby ..."
+  rbenv global 2.0.0-p247
+  rbenv rehash
+
+fancy_echo "Updating to latest Rubygems version ..."
+  gem update --system
+
+fancy_echo "Installing critical Ruby gems for Rails development ..."
+  gem install bundler rails compass --no-document
+### end common-components/ruby-environment
+
+fancy_echo "Installing Essential NPM Packages - Grunt, Yeoman and Bower, because you need them ..."
+  npm install -g yo grunt-cli bower
