new develop branch based on master, but adding all my other base install things with dotfiles, vagrant box, etc

diff --git a/mac b/mac
--- a/mac
+++ b/mac
@@ -1,37 +1,93 @@
 #!/usr/bin/env zsh
 
-successfully() {
-  $* || (echo "failed" 1>&2 && exit 1)
+# Welcome to Matt's laptop script! Forked from thoughbot.
+# Be prepared to turn your laptop (or desktop, no haters here)
+# into an awesome development machine.
+
+trap 'ret=$?; test $ret -ne 0 && printf "failed\n\n" >&2; exit $ret' EXIT
+
+set -e
+
+if [ ! -d "$HOME/.bin/" ]; then
+  mkdir "$HOME/.bin"
+fi
+
+fancy_echo() {
+  printf "\n%b\n" "$1"
 }
+
+if [[ -f /etc/zshenv ]]; then
+  fancy_echo "Fixing OSX zsh environment bug ..."
+    sudo mv /etc/{zshenv,zshrc}
+fi
 
 echo "Checking for SSH key, generating one if it doesn't exist ..."
   [[ -f ~/.ssh/id_rsa.pub ]] || ssh-keygen -t rsa
 
-echo "Fixing permissions ..."
-  successfully sudo chown -R `whoami` /usr/local
+fancy_echo "Installing Homebrew, a good OS X package manager ..."
+  ruby -e "$(curl -fsSL https://raw.github.com/mxcl/homebrew/go)"
+  brew update
 
-echo "Installing Homebrew, a good OS X package manager ..."
-  successfully ruby <(curl -fsS https://raw.github.com/mxcl/homebrew/go)
-  successfully brew update
+fancy_echo "Installing GNU Compiler Collection and dependencies ..."
+  brew tap homebrew/dupes
+  brew install coreutils autoconf openssl
 
-echo "Putting Homebrew location earlier in PATH ..."
-  successfully echo "
-# recommended by brew doctor
-export PATH='/usr/local/bin:$PATH'" >> ~/.zshenv
-  successfully source ~/.zshenv
+fancy_echo "Installing git, Node.js, Z Script ..."
+  brew install git node z
 
-echo "Installing GNU Compiler Collection and dependencies ..."
-  successfully brew tap homebrew/dupes
-  successfully brew install coreutils
+fancy_echo "Installing rbenv, to change Ruby versions ..."
+  brew install rbenv
+  exec zsh
 
-echo "Installing git, Node.js, Z Script ..."
-  successfully brew install git node z
+fancy_echo "Installing rbenv-gem-rehash so the shell automatically picks up binaries after installing gems with binaries..."
+  brew install rbenv-gem-rehash
 
-echo "Installing Essential NPM Packages - Grunt, Yeoman and Bower, because you need them ..."
-  successfully npm install -g yo grunt-cli bower
+fancy_echo "Installing ruby-build, to install Rubies ..."
+  brew install ruby-build
 
-echo "Installing critical Ruby gems for development ..."
-  successfully gem install bundler rails compass --no-rdoc --no-ri
+fancy_echo "Installing Ruby 2.0.0-p247 ..."
+  rbenv install 2.0.0-p247
+  exec zsh
 
-echo "Your shell will now restart in order for changes to apply."
-  exec $SHELL -l
+fancy_echo "Setting Ruby 2.0.0-p247 as global default Ruby ..."
+  rbenv global 2.0.0-p247
+  rbenv rehash
+  exec zsh
+
+fancy_echo "Updating to latest Rubygems version ..."
+  gem update --system
+
+fancy_echo "Installing critical Ruby gems for Rails development ..."
+  gem install bundler rails compass bourbon neat --no-document
+
+fancy_echo "Installing Essential NPM Packages - Grunt, Yeoman and Bower, because you need them ..."
+  npm install -g yo grunt-cli bower npm-check-updates
+
+fancy_echo "Clone and install dotfiles"
+  git clone https://github.com/mattbanks/dotfiles.git ~/.dotfiles
+  cd ~/.dotfiles
+  script/bootstrap
+  exec zsh
+
+fancy_echo "Install Source Code Pro Font"
+  fonts/copy
+
+fancy_echo "Setup iTerm2"
+  iterm2/setup
+
+fancy_echo "Setup Sublime Text 3"
+  sublime3/setup
+
+fancy_echo "Create Sites directory"
+  cd ~
+  mkdir ~/Sites
+
+fancy_echo "Setup hosts file to access Vagrant Dev Box"
+  sudo -- sh -c "echo \"\n##\n# Matt's hosts\n##\n192.168.204.72\tsites.whatup\n\" >> /etc/hosts"
+
+fancy_echo "Clone Vagrant box"
+  git clone https://github.com/mattbanks/vagrant-dev-box.git ~/vmdevbox
+
+fancy_echo "Setup OSX defaults"
+  cd ~/.dotfiles
+  osx/set-defaults.sh
